package ru.appkode.base.ui.movie.adapter

const val EVENT_ID_ADD_TO_WISHLIST_CLICKED = 0
const val EVENT_ID_OPEN_DETAILS = 1
const val EVENT_ID_MORE_INFORMATION_CLICKED = 2
const val EVENT_ID_ADD_TO_HISTORY_CLICKED = 3
const val EVENT_ITEM_DRAGGED_N_DROPPED = 4
const val EVENT_ITEM_SWIPED_RIGHT = 5
const val EVENT_ITEM_SWIPED_LEFT = 6
const val EVENT_SCREEN_REFRESH = 7